# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'pashirin-swiftui' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'GoogleMaps', '3.10.0'
	pod 'GooglePlaces', '3.10.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'lottie-ios'
  # Pods for pashirin-swiftui 

  target 'pashirin-swiftuiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
